#!/usr/bin/env bash
#
# The MIT License (MIT)
#
# Copyright (c) 2015-2026 Stephan Pauxberger
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <added-public-api.txt> <classified-inventory.tsv>" >&2
    exit 2
fi

input=$1
output=$2

if [[ ! -f "$input" ]]; then
    echo "Inventory does not exist: $input" >&2
    exit 2
fi

classify() {
    local artifact=$1
    local type=$2

    case "$artifact|$type" in
        klum-ast-annotations'|com.blackbuild.groovy.configdsl.transform.DelegatesToBuilder')
            echo 'client entrypoint|#394|export annotations package|4.x source and binary compatible'
            ;;
        klum-ast-annotations'|com.blackbuild.groovy.configdsl.transform.FieldType')
            echo 'generated hook|#474|export annotations package|4.x source and binary compatible after recompilation'
            ;;
        klum-ast-jackson'|com.blackbuild.klum.ast.jackson.KlumJacksonImporter'|\
        klum-ast-jackson'|com.blackbuild.klum.ast.jackson.KlumJacksonInput')
            echo 'client entrypoint|#463|export Jackson API package|4.x source and binary compatible'
            ;;
        klum-ast-runtime'|com.blackbuild.klum.ast.util.KlumObjectSupport'* )
            echo 'client entrypoint|#390|export runtime API package|4.x source and binary compatible'
            ;;
        klum-ast-runtime'|com.blackbuild.klum.ast.util.KlumBuilder'|\
        klum-ast-runtime'|com.blackbuild.klum.ast.util.KlumFactory'* )
            echo 'generated hook|#394/#431|export runtime API package for generated bytecode|4.x source and binary compatible after recompilation'
            ;;
        klum-ast-runtime'|com.blackbuild.klum.ast.process.PhaseAction'|\
        klum-ast-runtime'|com.blackbuild.klum.ast.process.BuilderVisitingPhaseAction'|\
        klum-ast-runtime'|com.blackbuild.klum.ast.process.ModelVisitingPhaseAction'|\
        klum-ast-runtime'|com.blackbuild.klum.ast.validation.InstanceValidator')
            echo 'extension seam|#305|export runtime or validation SPI package; no general SPI inferred|4.x source and binary compatible; direct providers retain ADR 0008 transition'
            ;;
        klum-ast-gradle-plugin'|'*)
            echo 'implementation|#434|published Gradle adapter only; no JPMS export commitment|not a 4.x client binary contract'
            ;;
        klum-ast-jackson'|'*)
            echo 'implementation|#463|internalize or qualified-export only for shipped Jackson linkage|not a 4.x client binary contract'
            ;;
        *)
            echo 'implementation|#468/#391|internalize; otherwise record generated/runtime linkage and use no general export|not a 4.x client binary contract'
            ;;
    esac
}

printf 'classification\towner\texport treatment\t4.x compatibility\tartifact\ttype\tkind\tdescriptor\n' > "$output"
while IFS='|' read -r artifact type kind descriptor; do
    IFS='|' read -r classification owner export_treatment compatibility < <(classify "$artifact" "$type")
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$classification" "$owner" "$export_treatment" "$compatibility" "$artifact" "$type" "$kind" "$descriptor" \
        >> "$output"
done < "$input"
