pluginManagement {
    repositories {
        maven { url = uri(klumRepository) }
        gradlePluginPortal()
    }
    plugins {
        id 'com.blackbuild.klum-ast-schema' version klumPluginVersion
        id 'com.blackbuild.klum-ast-model' version klumPluginVersion
    }
}
rootProject.name = 'portable-gdsl-binary-model'
