name: CI Groovy 3

on:
  push:
    branches: [ main, master, release-* ]
  pull_request:
    branches: [ main, master, release-* ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run:
          ./gradlew build --scan -PgroovyVersion=v3
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          check_name: 'JUnit Test Report G3'
      - name: Archive test classes
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test classes
          path: |
            **/build/test-classes/**/*.class
