name: CI JDK8

on:
  push:
    branches: [ main, master, release-* ]
  pull_request:
    branches: [ main, master, release-* ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
